[project]
  name = "personal-scripts"
  version = "0.1.0"
  description = "Add your description here"
  readme = "README.md"
  requires-python = ">=3.12"
  dependencies = [
    "exifread",
    "typer",
    "rich",
    "scipy>=1.16.3",
    "pandas>=2.3.3",
    "peewee>=3.18.3",
    "openpyxl>=3.1.5",
    "tqdm",
    "pillow>=10.0.0",
    "pillow-heif>=0.13.0",
  ]

[dependency-groups]
  dev = ["ipython", "pre-commit"]

[tool.ruff]
  target-version = "py314"
  line-length = 100

  [tool.ruff.lint]
    extend-select = ["E", "F", "UP", "W", "RUF"]
    ignore = ["RUF001", "RUF002", "RUF003"]
